name: babashka
on: [push]

jobs:
  bb-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquidz/babashka-test-action@v1.1
        with:
          source-paths: 'clj/script'
          test-paths: 'test/clj/script'
