name: dependencies
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  antq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquidz/antq-action@main
        # with:
        #   excludes: 'nrepl/nrepl cider/cider-nrepl@0.26.0 refactor-nrepl/refactor-nrepl@3.0.0-pr301'
