name: static
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '16'
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest
      - name: version check
        run: bash scripts/version_check.sh
      - name: deps check
        run: bash scripts/deps_check.sh
